Proje/Controllers/OgrenciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMVC.Models.EntityFramework;

namespace OgrenciNotMVC.Controllers
{
    public class OgrenciController : Controller
    {
        // GET: Ogrenci
        DbMvcOkulEntities db = new DbMvcOkulEntities();
        public ActionResult Index()
        {
            //Öğrenci Listeleme işlemi
            var OgrenciListele = db.TblOgrenci.ToList();
            return View(OgrenciListele);
        }

        [HttpGet]
        public ActionResult YeniOgrenci()
        {
            //DropdownListe Veri Yazdırma
            var deger = (from i in db.TblKulup.ToList()
                         select new SelectListItem
                         {
                             Text = i.KulupAd,
                             Value = i.Kulupid.ToString()
                         }).ToList();
            ViewBag.dgr = deger;
            return View();
        }

        [HttpPost]
        public ActionResult YeniOgrenci(TblOgrenci pEkle)
        {
            //DrownList veri tabana Ekleme kodu
            var klp = db.TblKulup.Where(m => m.Kulupid == pEkle.TblKulup.Kulupid).FirstOrDefault();
            pEkle.TblKulup = klp;

            //yeni Öğrenci Eklemek
            db.TblOgrenci.Add(pEkle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            //Ogrenci silme kodu
            var deger = db.TblOgrenci.Find(id);
            db.TblOgrenci.Remove(deger);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult OgrGetir(int id)
        {
            //DrownListe deger taşamak ve yazdırmak
            var kulup = (from i in db.TblKulup.ToList()
                         select new SelectListItem
                         {
                             Text = i.KulupAd,
                             Value = i.Kulupid.ToString()
                         }).ToList();
            ViewBag.dgr = kulup;

            //ogrenci id göre verileri taşama kodu
            var deger = db.TblOgrenci.Find(id);
            return View("OgrGetir", deger);
        }
        public ActionResult Guncelle(TblOgrenci p)
        {
            //Ogrenci Güncelleme kodu
            var deger = db.TblOgrenci.Find(p.Ogrid);
            deger.OgrAd = p.OgrAd;
            deger.OgrSoyad = p.OgrSoyad;
            deger.OgrFoto = p.OgrFoto;
            deger.OgrCinsiyet = p.OgrCinsiyet;

            //DropnList veri Güncelleme
            var ogr = db.TblKulup.Where(m => m.Kulupid == p.TblKulup.Kulupid).FirstOrDefault();
            deger.OgrKulup = ogr.Kulupid;

            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Proje/Views/Ogrenci/Index.cshtml
@using OgrenciNotMVC.Models.EntityFramework
@model List<TblOgrenci>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>OĞRENCİ İD</th>
        <th>AD</th>
        <th>SOYAD</th>
        <th>CİNSİYET</th>
        <th>KULÜP</th>
        <th>İŞLEMLER</th>
    </tr>
    <tbody>
        @foreach(var ogr in Model)
        {
        <tr>
            <td>@ogr.Ogrid</td>
            <td>@ogr.OgrAd</td>
            <td>@ogr.OgrSoyad</td>
            <td>@ogr.OgrCinsiyet</td>
            <td>@ogr.TblKulup.KulupAd</td>
            <td><a href="/Ogrenci/Sil/@ogr.Ogrid" class="btn btn-danger">Sil</a>
            <a href="/Ogrenci/OgrGetir/@ogr.Ogrid" class="btn btn-success">Güncelle</a></td>
        </tr>
        }
    </tbody>
</table>
<a href="/Ogrenci/YeniOgrenci" class="btn btn-primary">Yeni Öğrenci</a>

Proje/Views/Ogrenci/OgrGetir.cshtml
@model OgrenciNotMVC.Models.EntityFramework.TblOgrenci
@{
    ViewBag.Title = "OgrGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Ogrenci", FormMethod.Post))
{
    <div>
        <label><b>Öğrenci Ad</b></label>
        @Html.TextBoxFor(m => m.OgrAd, new { @class = "form-control" })
    </div>
    <br />
    <div>
        <label><b>Öğrenci Soyad</b></label>
        @Html.TextBoxFor(m => m.OgrSoyad, new { @class = "form-control" })
    </div>
    <br />
    <div>
        <label><b>Öğrenci Foto</b></label>
        @Html.TextBoxFor(m => m.OgrFoto, new { @class = "form-control" })
    </div>
    <br />
    <div>
        <label><b>Öğrenci Kulüp</b></label>
       @Html.DropDownListFor(m=>m.TblKulup.Kulupid, (List<SelectListItem>)ViewBag.dgr, new { @class="form-control"})
    </div>
    <br />
    <div>
        <label><b>Öğrenci Cinsiyet</b></label>
        @Html.TextBoxFor(m => m.OgrCinsiyet, new { @class = "form-control" })
    </div>
    <br />
    @Html.HiddenFor(m=>m.Ogrid)
    <div>
        <button class="btn btn-primary">Öğrenci Güncelle</button>
    </div>
}

Proje/Views/Ogrenci/YeniOgrenci.cshtml
@model OgrenciNotMVC.Models.EntityFramework.TblOgrenci
@{
    ViewBag.Title = "YeniOgrenci";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <div>
        <label><b>ÖĞRENİCİ AD</b></label>
        <input type="text" class="form-control" name="OgrAd" required="" maxlength="30" />
    </div>
    <br />
    <div>
        <label><b>ÖĞRENİCİ SOYAD</b></label>
        <input type="text" class="form-control" name="OgrSoyad" required="" maxlength="30" />
    </div>
    <br />
    <div>
        <label><b>ÖĞRENİCİ FOTO</b></label>
        <input type="text" class="form-control" name="OgrFoto" required="" maxlength="250" />
    </div>
    <br />
    <div>
        <label><b>ÖĞRENİCİ CİNSİYET</b></label>
        <br />
        @*<input type="text" class="form-control" name="OgrCinsiyet" required="" maxlength="10" />*@
        <input type="radio" id="kiz" name="OgrCinsiyet" value="Kız"/>
        <label for="kiz">Kız</label>
        <input type="radio" id="erkek" name="OgrCinsiyet" value="Erkek" style="margin-left:30px"/>
        <label for="erkek">Erkek</label>
    </div>
    <br />
    <div>
        <label><b>ÖĞRENİCİ KULÜP</b></label>
        @Html.DropDownListFor(m=>m.TblKulup.Kulupid, (List<SelectListItem>) ViewBag.dgr, new {@class="form-control"})
    </div>
    <br />
    <button class="btn btn-info">Öğrenci Ekle</button>
</form>