Proje/Controllers/NotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMVC.Models.EntityFramework;
using OgrenciNotMVC.Models;

namespace OgrenciNotMVC.Controllers
{
    public class NotController : Controller
    {
        // GET: Not
        DbMvcOkulEntities db = new DbMvcOkulEntities();
        public ActionResult Index()
        {
            //Not Listeleme Kodu
            var NotListele = db.TblNot.ToList();
            return View(NotListele);
        }

        [HttpGet]
        public ActionResult YeniNot()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniNot(TblNot pEkle)
        {
            //Yeni Not Ekleme kodu
            db.TblNot.Add(pEkle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult NotGetir(int id)
        {
            //id göre verileri deger sayfaya taşama kodu
            var deger = db.TblNot.Find(id);
            db.SaveChanges();
            return View("NotGetir", deger);
        }

        [HttpPost]
        public ActionResult NotGetir(Class1 model, TblNot p, int Viza=0, int Final=0, int But=0, int Proje=0)
        {
            if (model.islem == "Hesapla")
            {
                //hesaplama işlemi 
                int Ortalama = (Viza + Final + But + Proje) / 4;
                ViewBag.ort = Ortalama;
            }
            if (model.islem == "Guncelle")
            {
                //Not Güncelleme kodu
                var snv = db.TblNot.Find(p.Notid);
                snv.Viza = p.Viza;
                snv.Final = p.Final;
                snv.But = p.But;
                snv.Ortalama = p.Ortalama;
                snv.Proje = p.Proje;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Proje/Views/Not/Index.cshtml
@using OgrenciNotMVC.Models.EntityFramework
@model List<TblNot>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>NOT İD</th>
        <th>ÖĞRENCİ</th>
        <th>DERS</th>
        <th>VİZA</th>
        <th>FİNAL</th>
        <th>BÜT</th>
        <th>PROJE</th>
        <th>ORTALAMA</th>
        <th>DURUM</th>
        <th>GÜNCELLE</th>
    </tr>
    <tbody>
        @foreach (var not in Model)
        {
        <tr>
            <td>@not.Notid</td>
            <td>@not.Ogrid</td>
            <td>@not.Dersid</td>
            <td>@not.Viza</td>
            <td>@not.Final</td>
            <td>@not.But</td>
            <td>@not.Proje</td>
            <td>@not.Ortalama</td>
            <td>@not.Durum</td>
            <td><a href="/Not/NotGetir/@not.Notid" class="btn btn-warning">Güncelle</a></td>
        </tr>
        }
    </tbody>
</table>
<a href="/Not/YeniNot"  class="btn btn-primary">Yeni Not</a>

Proje/Views/Not/NotGetir.cshtml
@model OgrenciNotMVC.Models.EntityFramework.TblNot
@{
    ViewBag.Title = "NotGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("NotGetir", "Not", FormMethod.Post))
{
    <div>
        <label><b>Öğrenci id</b></label>
        @Html.TextBoxFor(m => m.Ogrid, new { @class = "form-control" })
    </div>
    <br />
    <div>
        <label><b>Viza</b></label>
        @Html.TextBoxFor(m => m.Viza, new { @class = "form-control" })
    </div>
    <br />
    <div>
        <label><b>Final</b></label>
        @Html.TextBoxFor(m => m.Final, new { @class = "form-control" })
    </div>
    <br />
    <div>
        <label><b>Büt</b></label>
        @Html.TextBoxFor(m => m.But, new { @class = "form-control" })
    </div>
    <br />
    <div>
        <label><b>Proje</b></label>
        @Html.TextBoxFor(m => m.Proje, new { @class = "form-control" })
    </div>
    <br />
    <div>
        <label><b>Ortalama</b></label>
        @Html.TextBoxFor(m => m.Ortalama, new {@Value= @ViewBag.ort, @class = "form-control" })
    </div>
    <br />
    <div>
        <label><b>Durum</b></label>
        @Html.TextBoxFor(m => m.Durum, new { @class = "form-control" })
    </div>
    <br />
    @Html.HiddenFor(m=>m.Notid)
<div>
    <button type="submit" name="islem" value="Hesapla" class="btn btn-default">Hesapla</button>
    <button type="submit" name="islem" value="Guncelle" class="btn btn-primary" style="margin-left:20px">Güncelle</button>
</div>
    
}

Proje/Views/Not/YeniNot.cshtml
@{
    ViewBag.Title = "YeniNot";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <div>
        <label><b>ÖĞRENİCİ İD</b></label>
        <input type="text" class="form-control" name="Ogrid" required=""/>
    </div>
    <br />
    <div>
        <label><b>DERS ADI</b></label>
        <input type="text" class="form-control" name="Dersid" required=""/>
    </div>
    <br />
    <div>
        <label><b>VİZA</b></label>
        <input type="text" class="form-control" name="Viza" required="" />
    </div>
    <br />
    <div>
        <label><b>FİNAL</b></label>
        <input type="text" class="form-control" name="Final" required=""/>
    </div>
    <br />
    <div>
        <label><b>BÜT</b></label>
        <input type="text" class="form-control" name="But" required="" />
    </div>
    <br />
    <div>
        <label><b>PROJE</b></label>
        <input type="text" class="form-control" name="Proje" required=""/>
    </div>
    <br />
    <div>
        <label><b>ORTALAMA</b></label>
        <input type="text" class="form-control" name="Ortalama" required=""/>
    </div>
    <br />
    <div>
        <label><b>DURUM</b></label>
        <input type="text" class="form-control" name="Durum" required="" />
    </div>
    <br />

    <button class="btn btn-info">Not Ekle</button>
</form>