Proje/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMVC.Models.EntityFramework;

namespace OgrenciNotMVC.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        DbMvcOkulEntities db = new DbMvcOkulEntities();
        public ActionResult Index()
        {
            //Dersleri Listeleme kodu
            var dersListesi = db.TblDers.ToList();
            return View(dersListesi);
        }

        [HttpGet]
        public ActionResult YeniDers()
        {
            //boş deger döndürmemesi için kod
            return View();
        }

        [HttpPost]
        public ActionResult YeniDers(TblDers pEkle)
        {
            //yeni ders eklemek için kod
            db.TblDers.Add(pEkle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            //Ders Silme kodu
            var deger = db.TblDers.Find(id);
            db.TblDers.Remove(deger);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DersGetir(int id)
        {
            //Deger sayfaya id göre veri taşama kodu
            var deger = db.TblDers.Find(id);
            return View("DersGetir",deger);
        }
        public ActionResult Guncelle(TblDers p)
        {
            var deger = db.TblDers.Find(p.Dersid);
            deger.DersAd = p.DersAd;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Proje/Views/Default/DersGetir.cshtml
@model OgrenciNotMVC.Models.EntityFramework.TblDers
@{
    ViewBag.Title = "DersGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Guncelle","Default", FormMethod.Post))
{
    <div>
        <label><b>Ders Ad</b></label>
        @Html.TextBoxFor(m=>m.DersAd, new { @class="form-control"})
    </div>
    <br />
    @Html.HiddenFor(m=>m.Dersid)
    <div>
        <button class="btn btn-primary">Ders Güncelle</button>
    </div>
}

Proje/Views/Default/Index.cshtml
@using OgrenciNotMVC.Models.EntityFramework
@model List<TblDers>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered" >
    <tr>
        <th>DERS İD</th>
        <th>DERS ADI</th>
        <th>İŞLEMLER</th>
    </tr>
    <tbody>
        @foreach (var drs in Model)
        {
            <tr>
                <td>@drs.Dersid</td>
                <td>@drs.DersAd</td>
                <td><a href="/Default/Sil/@drs.Dersid" class="btn btn-danger">Sil</a>
                <a href="/Default/DersGetir/@drs.Dersid" class="btn btn-success">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/Default/YeniDers" class="btn btn-primary">Yeni Ders</a>

Proje/Views/Default/YeniDers.cshtml
@{
    ViewBag.Title = "YeniDers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <dv>
        <label><b>Ders Adı</b></label>
        <input type="text" name="DersAd" required="" maxlength="50" class="form form-control" />
    </dv>
    <br />
    <div>
        <button class="btn btn-info">Ders Ekle</button>
    </div>
</form>