Proje/Controllers/KulupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMVC.Models.EntityFramework;

namespace OgrenciNotMVC.Controllers
{
    public class KulupController : Controller
    {
        // GET: Kulup
        DbMvcOkulEntities db = new DbMvcOkulEntities();
        public ActionResult Index()
        {
            //Kulup Listeleme Kodu
            var KulupListele = db.TblKulup.ToList();
            return View(KulupListele);
        }
        
        [HttpGet]
        public ActionResult YeniKulup()
        {
            //nul deger döndürmemesi için kod
            return View();
        }

        [HttpPost]
        public ActionResult YeniKulup(TblKulup pEkle)
        {
            //kulup ekleme kodu
            db.TblKulup.Add(pEkle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            //Kulup Silme kodu
            var deger = db.TblKulup.Find(id);
            db.TblKulup.Remove(deger);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KulupGetir(int id)
        {
            //id göre veri taşama kodu
            var deger = db.TblKulup.Find(id);
            return View("KulupGetir",deger);
        }
        public ActionResult Guncelle(TblKulup p)
        {
            //Kulup Güncelleme kodu
            var deger = db.TblKulup.Find(p.Kulupid);
            deger.KulupAd = p.KulupAd;
            deger.KulupKontenjan = p.KulupKontenjan;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Proje/Views/Kulup/Index.cshtml
@using OgrenciNotMVC.Models.EntityFramework
@model List<TblKulup>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>KULÜP İD</th>
        <th>KULÜP ADI</th>
        <th>KULÜP KONTENJAN</th>
        <th>İŞLEMLER</th>
    </tr>
    <tbody>
        @foreach(var klp in Model)
        {
            <tr>
                <td>@klp.Kulupid</td>
                <td>@klp.KulupAd</td>
                <td>@klp.KulupKontenjan</td>
                <td><a href="/Kulup/Sil/@klp.Kulupid" class="btn btn-danger">Sil</a>
                <a href="/Kulup/KulupGetir/@klp.Kulupid" class="btn btn-success">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/Kulup/YeniKulup" class="btn btn-primary">Yeni Kulüp</a>

Proje/Views/Kulup/KulupGetir.cshtml
@model OgrenciNotMVC.Models.EntityFramework.TblKulup
@{
    ViewBag.Title = "KulupGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Kulup", FormMethod.Post))
{
    <div>
        <label><b>Kulüp Ad</b></label>
        @Html.TextBoxFor(m => m.KulupAd, new { @class = "form-control" })
    </div>
    <br />
    <div>
        <label><b>Kulüp Kontenjan</b></label>
        @Html.TextBoxFor(m => m.KulupKontenjan, new { @class = "form-control" })
    </div>
    <br />
    @Html.HiddenFor(m => m.Kulupid)
    <div>
        <button class="btn btn-primary">Kulüp Güncelle</button>
    </div>
}

Proje/Views/Kulup/YeniKulup.cshtml
@{
    ViewBag.Title = "YeniKulup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <div>
        <label><b>Kulüp Adı</b></label>
        <input type="text" class="form-control" name="KulupAd" required="" maxlength="30" />
    </div>
    <br />
    <div>
        <label><b>Kulüp Kontenjan</b></label>
        <input type="text" class="form-control" name="KulupKontenjan" required=""/>
    </div>
    <br />
    <button class="btn btn-info">Kulüp Ekle</button>
</form>